name: Camille Charlotte
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9694052617996931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e68bac'
    - '#231f20'
    - '#cacaca'
    - '#858585'
  brandStrength: 0.1875
  lightness: 0.8993545102421194
  saturation: 0.38060468598268926
  rhythmicContrast: 0.4649872723966837
purpose: []
