name: Camille Charlotte
favicon: null
layout_spectrum: 0.92993
typography_spectrum: 0.59739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b80ce'
    - '#f0d3fa'
    - '#f7a5f4'
    - '#333333'
    - '#bdc92f'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
