name: Camille Charlotte
favicon: null
layout_spectrum: 0.17493814113549888
typography_spectrum: 0.9694052617996931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16549622709862888
  lightness: 0.8993545102421194
  saturation: 0.38060468598268926
  rhythmicContrast: 0.4649872723966837
purpose: []
